//! Scans `../applications/*/manifest.txt` and emits a Rust source file
//! at `$OUT_DIR/app_registry_generated.rs` that the kernel includes via
//! `src/app_registry.rs`. Each manifest becomes one entry in a static
//! `APPS` slice; ELF apps get their bytes embedded via `include_bytes!`.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Rerun whenever anything under applications/ changes.
    let apps_dir = PathBuf::from("../applications");
    println!("cargo:rerun-if-changed={}", apps_dir.display());

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("app_registry_generated.rs");

    let mut entries: Vec<Entry> = Vec::new();

    if apps_dir.is_dir() {
        let mut dirs: Vec<_> = fs::read_dir(&apps_dir)
            .expect("read applications/")
            .filter_map(|d| d.ok())
            .filter(|d| d.path().is_dir())
            .map(|d| d.path())
            .collect();
        dirs.sort();

        for dir in dirs {
            let manifest = dir.join("manifest.txt");
            println!("cargo:rerun-if-changed={}", manifest.display());
            if !manifest.is_file() {
                continue;
            }
            let text = fs::read_to_string(&manifest)
                .unwrap_or_else(|e| panic!("reading {}: {}", manifest.display(), e));
            let kv = parse_manifest(&text);
            match build_entry(&dir, &kv) {
                Ok(entry) => {
                    if let Entry::Elf { elf_path, .. } = &entry {
                        println!("cargo:rerun-if-changed={}", elf_path.display());
                    }
                    entries.push(entry);
                }
                Err(e) => panic!("{}: {}", manifest.display(), e),
            }
        }
    }

    let rendered = render(&entries);
    fs::write(&out_path, rendered).expect("writing app_registry_generated.rs");
}

enum Entry {
    Builtin {
        name: String,
        window_kind: String,
    },
    Elf {
        name: String,
        elf_path: PathBuf,
    },
}

fn parse_manifest(text: &str) -> BTreeMap<String, String> {
    let mut kv = BTreeMap::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((k, v)) = line.split_once('=') {
            kv.insert(k.trim().to_string(), v.trim().to_string());
        }
    }
    kv
}

fn build_entry(dir: &Path, kv: &BTreeMap<String, String>) -> Result<Entry, String> {
    let name = kv
        .get("name")
        .ok_or_else(|| String::from("missing `name`"))?
        .clone();
    let kind = kv
        .get("kind")
        .map(|s| s.as_str())
        .ok_or_else(|| String::from("missing `kind`"))?;

    match kind {
        "builtin" => {
            let window_kind = kv
                .get("window_kind")
                .ok_or_else(|| String::from("builtin apps need `window_kind`"))?
                .clone();
            Ok(Entry::Builtin { name, window_kind })
        }
        "elf" => {
            let binary = kv
                .get("binary")
                .ok_or_else(|| String::from("elf apps need `binary`"))?;
            let elf_path = dir.join(binary);
            if !elf_path.is_file() {
                return Err(format!("binary `{}` not found", elf_path.display()));
            }
            // include_bytes! wants an absolute path when invoked from a
            // generated file under OUT_DIR.
            let abs = fs::canonicalize(&elf_path).map_err(|e| e.to_string())?;
            Ok(Entry::Elf {
                name,
                elf_path: abs,
            })
        }
        other => Err(format!("unknown kind `{}`", other)),
    }
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn render(entries: &[Entry]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by kernel/build.rs from ../applications/*/manifest.txt\n");
    out.push_str("// Do not edit by hand — `cargo build` regenerates this.\n\n");

    out.push_str("#[derive(Copy, Clone)]\n");
    out.push_str("pub enum AppKind {\n");
    out.push_str("    Builtin(crate::window::WindowKind),\n");
    out.push_str("    Elf(&'static [u8]),\n");
    out.push_str("}\n\n");

    out.push_str("pub struct AppEntry {\n");
    out.push_str("    pub name: &'static str,\n");
    out.push_str("    pub kind: AppKind,\n");
    out.push_str("}\n\n");

    out.push_str("pub static APPS: &[AppEntry] = &[\n");
    for e in entries {
        match e {
            Entry::Builtin { name, window_kind } => {
                writeln!(
                    &mut out,
                    "    AppEntry {{ name: \"{}\", kind: AppKind::Builtin(crate::window::WindowKind::{}) }},",
                    escape(name),
                    window_kind,
                )
                .unwrap();
            }
            Entry::Elf { name, elf_path } => {
                writeln!(
                    &mut out,
                    "    AppEntry {{ name: \"{}\", kind: AppKind::Elf(include_bytes!(\"{}\")) }},",
                    escape(name),
                    escape(&elf_path.display().to_string()),
                )
                .unwrap();
            }
        }
    }
    out.push_str("];\n");
    out
}
